import { Box, Button, Collapse, Divider, Heading, HStack, Image, Text, VStack } from "@chakra-ui/react";
import Head from "next/head";

import CoursesList from "../components/courses_list/courses_list";
import Header from "../components/header/header";
import HeaderMenu from "../components/header/header_menu";
import HeaderOffer from "../components/header/header_offer";
import {
    Accordion,
    AccordionItem,
    AccordionButton,
    AccordionPanel,
    AccordionIcon,
  } from '@chakra-ui/react'

import { useState } from "react";
import { DownloadIcon, EmailIcon } from "@chakra-ui/icons";
import Footer from "../components/footer/footer";

export default function Details() {
    const [show, setShow] = useState(false);

    const handleToggle = () => setShow(!show);
 
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Header />
    <Divider></Divider>

    <VStack alignItems={'start'} >
    <HStack pt={5}  pr={200}  pl={200} backgroundColor={'#1c1d1f'} w={'100%'} height={'20.8rem'} display='flex' justifyItems='start' justifyContent={'space-between'} alignItems='center' >        
        <VStack alignItems={'start'}   >
        <Text color={'#cec0fc'} fontWeight='bold' fontSize={15}  >Desenvolvimento - Data Sciente - Inteligecia artificial</Text>
        <Heading color={'white'} >Inteligencia Artificla e Machine Learning o Guia completo</Heading>
        <Text color={'white'}>Quer estudar IA e não sabe por onde começar? <br></br> Aqui você aprende tudo o que precisa saber sobre a área na teoria e prática </Text>
        <Text color={'white'}>rating</Text>
        <Text color={'white'}>Autor</Text>
        <Text color={'white'}>Ultima atualização</Text>
        
        </VStack>
        <Box mb={10}  zIndex='1' width={400} backgroundColor="black" p={0.5} pb={5} justifyContent={'center'}  boxShadow='lg'  bg='white' alignSelf={'flex-start'}>
            <Image  src="https://img-c.udemycdn.com/course/240x135/1708340_7108_5.jpg"w={'100%'}></Image>
            <VStack pt={5} pl={5} pr={5} display='flex' alignItems={'flex-start'}>

            <HStack  >
            <Heading>R$27,90 </Heading>
            <Text textDecoration={'line-through'} color='grey' fontSize={14}>R$1.237,90</Text>
            </HStack>
            <Text fontSize={14} color='grey'>Muitos por cento de desconto</Text>
            <HStack>
            
            <Text fontSize={14}>Só mais 1 hora nesse preço</Text>
            </HStack>
            <HStack display={'flex'} justifyContent='space-between' width={'100%'}>

            <Button  color={'white'} backgroundColor={'#a435f0'} borderRadius='0' flex={1}>

                Adicionar ao carrinho
            </Button>
            <Button borderRadius='0' border={'1px solid'}  backgroundColor='transparent'>

                {`<3`}
                
            </Button>


            </HStack>
            <Button w={'100%'} backgroundColor='transparent' border={'1px solid'} borderRadius='0'>
                Comprar agora
            </Button>
            <Text w={'100%'} align='center'  fontSize='12px' color={'grey'}>
                Garantia de devolução em 30 dias
            </Text>

            <Text fontWeight={'bold'} fontSize='17px'>
                Este curso inclui

            </Text>

            <HStack>
            <EmailIcon></EmailIcon>
                <Text fontSize='14px' color={'grey'} > 25 horas</Text>
            </HStack>
            <HStack>
                <DownloadIcon></DownloadIcon>
                <Text fontSize='14px' color={'grey'}>29 artigos</Text>
            </HStack>
            <HStack>
                <DownloadIcon></DownloadIcon>
                <Text fontSize='14px' color={'grey'}>Acesso total vitalicio</Text>
            </HStack>
            <HStack>
                <DownloadIcon></DownloadIcon>
                <Text fontSize='14px' color={'grey'}>Acesso no dispositivo movel ou tv</Text>
            </HStack>
            </VStack>
        </Box>
    </HStack>
    
    <VStack alignItems={'start'}  pr={200}  pl={200}  >

        <Box height={'100%'} w="60%"  border={'0.5px solid'} borderColor='grey' p={10} >

        <Heading>O que você aprenderá</Heading>
        <Text>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore 
            et dolore magna aliqua. Ut enim ad minim veniam, 
            quis nostrud exercitation ullamco laboris nisi ut 
            aliquip ex ea commodo consequat. Duis aute irure dolor 
            in reprehenderit in voluptate velit esse cillum dolore eu 
            fugiat nulla pariatur. Excepteur sint occaecat cupidatat non 
            proident, sunt in culpa qui officia deserunt mollit anim id est laborum</Text>
        <Text>Quer estudar IA e não sabe por onde começar? <br></br> Aqui você aprende tudo o que precisa saber sobre a área na teoria e prática </Text>
        <Text>rating</Text>
        <Text>Autor</Text>
        <Text>Ultima atualização</Text>
        </Box>
     
        <Box height={'100%'} w="60%"  border={'0.5px solid'} borderColor='grey' p={10} >

        <Text>Nossas empresas ofereceem esse curso para seus funcionarios</Text>
        <Text>Esse curso foi selecionado para nosso acervo de cursos conceituados utilizados por empresas de todo o mundo. Saiba mais</Text>
        <HStack mt={5}  display={'flex'} justifyContent='space-between' >

            <Image src="https://s.udemycdn.com/partner-logos/v4/nasdaq-dark.svg" ></Image>
            <Image src="https://s.udemycdn.com/partner-logos/v4/volkswagen-dark.svg" ></Image>
            <Image src="https://s.udemycdn.com/partner-logos/v4/box-dark.svg" ></Image>
            <Image src="https://s.udemycdn.com/partner-logos/v4/netapp-dark.svg" ></Image>
       

        </HStack>
       
    
        </Box>

   <Box w={'60%'} >
   <Accordion>
  <AccordionItem>
    <h2>
      <AccordionButton>
        <Box flex='1' textAlign='left'>
          Section 1 title
        </Box>
        <AccordionIcon />
      </AccordionButton>
    </h2>
    <AccordionPanel pb={4}>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
      veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
      commodo consequat.
    </AccordionPanel>
  </AccordionItem>

  <AccordionItem>
    <h2>
      <AccordionButton>
        <Box flex='1' textAlign='left'>
          Section 2 title
        </Box>
        <AccordionIcon />
      </AccordionButton>
    </h2>
    <AccordionPanel pb={4}>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
      veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
      commodo consequat.
    </AccordionPanel>
  </AccordionItem>
  <AccordionItem>
    <h2>
      <AccordionButton>
        <Box flex='1' textAlign='left'>
          Section 2 title
        </Box>
        <AccordionIcon />
      </AccordionButton>
    </h2>
    <AccordionPanel pb={4}>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
      veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
      commodo consequat.
    </AccordionPanel>
  </AccordionItem>
  <AccordionItem>
    <h2>
      <AccordionButton>
        <Box flex='1' textAlign='left'>
          Section 2 title
        </Box>
        <AccordionIcon />
      </AccordionButton>
    </h2>
    <AccordionPanel pb={4}>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
      veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
      commodo consequat.
    </AccordionPanel>
  </AccordionItem>
  <AccordionItem>
    <h2>
      <AccordionButton>
        <Box flex='1' textAlign='left'>
          Section 2 title
        </Box>
        <AccordionIcon />
      </AccordionButton>
    </h2>
    <AccordionPanel pb={4}>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
      veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
      commodo consequat.
    </AccordionPanel>
  </AccordionItem>
  <AccordionItem>
    <h2>
      <AccordionButton>
        <Box flex='1' textAlign='left'>
          Section 2 title
        </Box>
        <AccordionIcon />
      </AccordionButton>
    </h2>
    <AccordionPanel pb={4}>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
      veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
      commodo consequat.
    </AccordionPanel>
  </AccordionItem>
</Accordion>


    
   </Box>
   <Box>

   <Heading>Requisitos</Heading>
   <Text>Lógica de programação, principalmente estruturas condicionais e de repetição|</Text>
   <Text>Conhecimentos sobre instalação de softwares básicos, porém, durante o curso será mostrado o processo de instalação das ferramentas utilizadas</Text>
   <Text>Noções de Orientação a Objetos, como: classes, objetos, atributos e métodos</Text>
   <Text>Conhecimentos básicos sobre Redes Neurais Artificiais são desejáveis (no final do curso tem um anexo para revisar esse conteúdo)</Text>
   </Box>

        

        </VStack>
    </VStack>
  

    <Footer></Footer>

     
      


    </>
  );
}
