import { Box, Button, Modal, ModalBody, ModalCloseButton, ModalContent, ModalFooter, ModalHeader, ModalOverlay, Text, useDisclosure } from "@chakra-ui/react";
import Head from "next/head";
import { useEffect, useState } from "react";
import { Signup } from "../components/signup/Signup";

export default function Home() {

  const { isOpen, onOpen, onClose } = useDisclosure()

  const [step, setSteps] = useState(0)

  useEffect(() => {

    onOpen()
  }, [])

function handleNextStep(){

  var nextStep: number = step + 1

setSteps(nextStep)

}

function handlePreviousStep(){

  var previous: number = step - 1

setSteps(previous)

}

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Modal isOpen={isOpen} onClose={onClose}>
        <ModalOverlay />
        <ModalContent>
          <ModalHeader>Bem vindo</ModalHeader>
          <ModalCloseButton />
          <ModalBody>
            <Text>Precisamos de alguns dados para cadastrar começar a sua integração</Text>
          
          </ModalBody>

          <ModalFooter>
            <Button colorScheme='blue' mr={3} onClick={onClose}>
              Entendi
            </Button>
       
          </ModalFooter>
        </ModalContent>
      </Modal>

      <Signup step={step} nextStep={() => {
        handleNextStep()
      }} previousStep={handlePreviousStep} />
  
    </>
  );
}
